### ISSUE TITLE
Query Pypi for version, description, website and license

### ISSUE THREAD

**Issue by SuperSandro2000** [jonringer/nix-template#11]
It would be really useful for packaging python things if the tool would query pypi for the latest released version, description, website and license.

**Comment by jonringer** [comment]
I was thinking of doing a `--from-url=...` and having one for github and pypi.

Now that hte release is over, I'll probably improve this utility a bit more

**Comment by jonringer** [comment]
half implemented in #13, just need to add pypi support, also probably refactor the code so that adding more upstreams becomes easier

**Comment by jonringer** [comment]
added in https://github.com/jonringer/nix-template/commit/cfc307dbf1b3e590355d1fed6bd02394684a729a
