### ISSUE TITLE
completions fail to load

### ISSUE THREAD

**Issue by Artturin** [jonringer/nix-template#16]
i put 
```
eval "$(nix-template completions zsh)"
```
in my zshrc

i get `_arguments: command not found` when i start a new shell

happens without a config too
```
env -i zsh -d -f -i
eval "$(nix-template completions zsh)"
```

**Comment by jonringer** [comment]
looks like this is a zsh issue https://github.com/clap-rs/clap/issues/2014#issuecomment-673039994

I'll fix this in the nix expression once I update

**Comment by jonringer** [comment]
Installing the 0.1.3 version through nix should fix completions:
```
$ tree ./result/share/
./result/share/
├── bash-completion
│   └── completions
│       └── nix-template.bash
├── fish
│   └── vendor_completions.d
│       └── nix-template.fish
└── zsh
    └── site-functions
        └── _nix-template
```

**Comment by Artturin** [comment]
nope its not working but no errors

**Comment by Artturin** [comment]
well now it works i had to run compinit manually for some reason

**Comment by jonringer** [comment]
completions were added to nixpkgs unstable
