### ISSUE TITLE
suggestion:  style

### ISSUE THREAD

**Issue by Artturin** [jonringer/nix-template#18]
use 
```
{ lib
, stdenv
, fetchFromGitHub 
}:
```
instead of 
```{ lib, stdenv, fetchFromGitHub }:```

btw what is the name of this i still haven't found out

**Comment by jonringer** [comment]
sure, I can add a new line

**Comment by NerdyPepper** [comment]
>btw what is the name of this i still haven't found out

It is called the "comma-leading style" from what I've learnt.
