### ISSUE TITLE
Change hash type to SRI

### ISSUE THREAD

**Issue by Kranzes** [jonringer/nix-template#41]
Change the hash generated:
`0q69n3nyal57h3ik2xirwzrxzljrwy9ivwraxzv9566vi3n4z5mw` -> `sha256-vJZP7IjbmJL27yrzHZPnWdLf8+c5djHjgKdQ5e2wyWA=`

**Comment by jonringer** [comment]
Yea, I could do this, it's just a `nix hash to-sri --type sha256` call.

**Comment by jonringer** [comment]
actually, this might be a bit more involved, as I believe people need to have `nix command` experimental feature
